### ISSUE TITLE
Incorrect "unused definition warning" when using allOf and $ref

### ISSUE THREAD

**Issue by mohsen1** [apigee-127/swagger-tools#216]
From https://github.com/swagger-api/swagger-editor/issues/464
With this YAML, Swagger Tools throws following warning which I believe is incorrect:
```
Definition is defined but is not used: #/definitions/I1/allOf/1
```
```yaml
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/I1'
definitions:
  Base:
    properties:
      f1:
        type: string
      f2:
        type: integer
        format: int32
    required:
    - f1
  I1:
    type: object
    allOf:
      - $ref: '#/definitions/Base'
      - properties:
          f3:
            type: string
```

**Comment by whitlockjc** [comment]
You've reported this a handful of times now.  This was already fixed and was released with 0.8.7 today.  I just verified that this does not happen with the latest release in NPM.  Please upgrade.

**Comment by PSDCoder** [comment]
Hi, I just pulled swagger-editor and launched it with swagger-tools version 0.8.7. Error still present.

**Comment by PSDCoder** [comment]
If it helps, my example:
```yaml
swagger: '2.0'
info:
  title: test api
  version: "0.0.1"
host: api.some.com
paths:
  /news:
    get:
      summary: Get news.
      tags:
        - News
      responses:
        200:
          description: List of news
          schema:
            type: array
            items: 
              $ref: '#/definitions/News'
definitions:
  CreatedUpdated:
    type: object
    required:
      - createdAt
      - updatedAt
    properties:
      createdAt:
        type: string
        format: dateTime
        description: Date when news was created.
      updatedAt: 
        type: string
        format: dateTime
        description: Date when news was update last.
  News:
    type: object
    allOf:
      - $ref: '#/definitions/CreatedUpdated'
      - required:
          - id
          - title
          - slug
          - image
          - text
        properties:
          id:
            type: string
            format: int64
            description: Database identifier, unique.
          title:
            type: string
            description: Title of news.
          slug:
            type: string
            description: Url-safe title.
          image: 
            type: string
            description: Url to header news image.
          text: 
            type: string
            format: html
            description: Text of news.
```

But if we move mixed object data to new definition (NewsBase) and use it as $ref then it will works:
```yaml
swagger: '2.0'
info:
  title: test api
  version: "0.0.1"
host: api.some.com
paths:
  /news:
    get:
      summary: Get news.
      tags:
        - News
      responses:
        200:
          description: List of news
          schema:
            type: array
            items: 
              $ref: '#/definitions/News'
definitions:
  CreatedUpdated:
    type: object
    required:
      - createdAt
      - updatedAt
    properties:
      createdAt:
        type: string
        format: dateTime
        description: Date when news was created.
      updatedAt: 
        type: string
        format: dateTime
        description: Date when news was update last.
  NewsBase:
    type: object
    required:
      - id
      - title
      - slug
      - image
      - text
    properties:
      id:
        type: string
        format: int64
        description: Database identifier, unique.
      title:
        type: string
        description: Title of news.
      slug:
        type: string
        description: Url-safe title.
      image: 
        type: string
        description: Url to header news image.
      text: 
        type: string
        format: html
        description: Text of news.
  News:
    type: object
    allOf:
      - $ref: '#/definitions/NewsBase'
      - $ref: '#/definitions/CreatedUpdated'
```

**Comment by whitlockjc** [comment]
I'll try to reproduce again but this appears to be a duplicate of #187 and I was unable to reproduce it with the latest CLI release using `swagger-tools valudate`.

**Comment by whitlockjc** [comment]
Even using your YAML when I run `swagger-tools validate swagger.yaml`, I do not get any errors.  Here is the verbose output:

```
Validation Details:

  Swagger Version: 2.0
  Swagger file: testing.yaml

Swagger document is valid
```

I even tried the web build of swagger-tools and what gets logged to the console is `undefined`:

```js
SwaggerTools.specs.v2.validate({
  "swagger": "2.0",
  "info": {
    "title": "test api",
    "version": "0.0.1"
  },
  "host": "api.some.com",
  "paths": {
    "/news": {
      "get": {
        "summary": "Get news.",
        "tags": [
          "News"
        ],
        "responses": {
          "200": {
            "description": "List of news",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/News"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CreatedUpdated": {
      "type": "object",
      "required": [
        "createdAt",
        "updatedAt"
      ],
      "properties": {
        "createdAt": {
          "type": "string",
          "format": "dateTime",
          "description": "Date when news was created."
        },
        "updatedAt": {
          "type": "string",
          "format": "dateTime",
          "description": "Date when news was update last."
        }
      }
    },
    "NewsBase": {
      "type": "object",
      "required": [
        "id",
        "title",
        "slug",
        "image",
        "text"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "int64",
          "description": "Database identifier, unique."
        },
        "title": {
          "type": "string",
          "description": "Title of news."
        },
        "slug": {
          "type": "string",
          "description": "Url-safe title."
        },
        "image": {
          "type": "string",
          "description": "Url to header news image."
        },
        "text": {
          "type": "string",
          "format": "html",
          "description": "Text of news."
        }
      }
    },
    "News": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/NewsBase"
        },
        {
          "$ref": "#/definitions/CreatedUpdated"
        }
      ]
    }
  }
}, function (err, results) {
  if (err) {
    throw err;
  } else {
    console.log(results);
  }
});
```

I cannot reproduce this.  When #187 was reported, I was able to reproduce this without issue but I am unable to do so now that v0.8.7 has been released.
