### ISSUE TITLE
Supporting $ref to relative path

### ISSUE THREAD

**Issue by hhp21** [apigee-127/swagger-tools#227]
I have a Swagger 2.0 spec `api/spec.json` and inside there I want to have a reference to a local file `api/defs.json` for my definitions. So in `spec.json` I'm doing something like:

```
    "/message": {
      "post": {
        "parameters": [{
          "name": "message",
          "in": "body",
          "schema": {
            "$ref": "defs.json"
          }
```
where `defs.json` looks like
```
{
    "properties": {
      "text": {
        "type": "string"
      }
    },
    "required": ["text"]
}
```

But I just get `#/paths/~1message/post/parameters/0/schema/$ref: Not a valid JSON Reference` on init

I've tried several variations like:
```
"$ref" : "./defs.json"
```
This starts but fails with `#: Reference could not be resolved: ./defs.json` when a request is sent.

I have read that $ref supports internal and remote (with an absolute URL), but not been able to find any documentation on relative paths.

Here is a mention that this might be possible already: https://github.com/swagger-api/swagger-spec/issues/275#issuecomment-95232922
Here is a mention that it has just been implemented in swagger-js: https://github.com/swagger-api/swagger-js/issues/417

Are relative paths supported at all?

**Comment by whitlockjc** [comment]
JSON Reference resolution is handled by json-refs and there is a known issue for supporting this: [whitlockjc/json-refs/issues/11](https://github.com/whitlockjc/json-refs/issues/11).  I will keep this open in here until this issue is resolved in json-refs.

**Comment by glen-84** [comment]
@whitlockjc Is there any news on this? Absolute URLs are far from ideal.

**Comment by whitlockjc** [comment]
This *should* be fixed but there is currently a bug in [json-refs/issues/24](https://github.com/whitlockjc/json-refs/issues/24) that you need to be careful of.  No circular remote/relative references?  Things will work like you want.

**Comment by glen-84** [comment]
@whitlockjc,

It's not working for me. Am I doing something wrong?

http://pastie.org/private/0ozh5wm8li9qrrifl9cbua (swagger.yaml)
http://pastie.org/private/6coezsiq2d9bmawl4yygg (definitions/models/videos/video.yaml)

**Comment by whitlockjc** [comment]
How are you loading swagger.yaml?

**Comment by glen-84** [comment]
With Swagger UI.

Also, it seems to request the main file 8 times when I reference the video file, but it doesn't request the video file itself.

**Comment by whitlockjc** [comment]
swagger-ui does not support relative references.

**Comment by whitlockjc** [comment]
I'm going to reopen the issue until I have unit tests showing it works but swagger-ui is not related to swagger-tools.

**Comment by glen-84** [comment]
Thanks @whitlockjc, I guess it's this one: https://github.com/swagger-api/swagger-ui/issues/1456.

**Comment by oliverhr** [comment]
It would be great to be able to run this example:

https://github.com/swagger-api/swagger-spec/tree/master/examples/v2.0/yaml/petstore-separate

**Comment by whitlockjc** [comment]
The problem we have right now with supporting this is that swagger-tools does not know where the original document was loaded from so doing relative reference resolution isn't possible without providing that context.  swagger-tools uses [path-loader](https://github.com/whitlockjc/path-loader) and [json-refs](https://github.com/whitlockjc/json-refs) which both support relative references but they do it based on `process.cwd` on Node.js and `window.location` in the browser.  Whenever the location of the loaded document is not known and does not conform to the aforementioned defaults, the related json-refs/path-loader APIs have an `options.location` option to fill in the gap.

That being said, to support this I would need to update all APIs in swagger-tools to support passing this option to json-refs/path-loader.  It's not impossible but it would change the APIs a bit.  I need to think about this a little more.

**Comment by NitroPye** [comment]
I'm having a little tough time following, is this only an issue only with swagger-ui? I'm unable to get it to work using the swagger-node module loading swagger.yaml (completely in node, no browser in the chain at all)

Relevant snippet

swagger.yaml (snipped)
```
        default:
          description: Error
          schema:
            $ref: "error.yaml#/ErrorResponse"
```

error.yaml
```
ErrorResponse:
  required:
    - errors
  properties:
    errors:
      type: array
      items:
        $ref: "#Error"
```

Then when running swagger-node's validate I get this:
```
swagger validate api/swagger/swagger.yaml 

Project Errors
--------------
#/paths/~1events/get/responses/default/schema/$ref: Not a valid JSON Reference
Results: 1 errors, 0 warnings
```

**Comment by whitlockjc** [comment]
Your `#Error` reference is wrong.  It should be `#/definitions/Error`.

**Comment by NitroPye** [comment]
Good catch although it appears to be tangential. I changed errors.yaml as a test to be:

```
ErrorResponse:
  required:
    - errors
  properties:
    errors:
      type: string
```

**Comment by whitlockjc** [comment]
What's the error now?  I doubt swagger-node supports relative references just yet since it uses swagger-tools which is known not to support relative references except under certain conditions.

**Comment by NitroPye** [comment]
Sorry I should have been more clear. Its the same error as before. Under what conditions does swagger-tools support relative references? I could maybe force them or look thru swagger-node to figure out how to get them to work.

**Comment by whitlockjc** [comment]
The paths must be relative to `process.cwd` which is not ideal of course.  So for swagger-node, your relative references would start with `./api/swagger`.  So if you had a `users.yaml` in `api/swagger`, you'd have something like this:

```yaml
# ...
  $ref: './api/swagger/users.yaml#/definitions/User'
# ..
```

**Comment by glen-84** [comment]
Not sure if it's relevant, but what we're doing is using [swagger-parser](https://github.com/BigstickCarpet/swagger-parser) (3.0.0-alpha.5) to dereference our swagger.yaml file (with relative paths), and then we save it as swagger.json and serve that.

**Comment by whitlockjc** [comment]
swagger-tools dereferences references too but relative references weren't a thing until recently.  When we started work on breaking up swagger-tools, we started [swagger-core-api](https://github.com/apigee-127/swagger-core-api) and it does work with relative references.  In face, swagger-core-api does better validation than swagger-tools at this point.  The reason I bring this up is swagger-tools will be deprecated in the future and will be replaced by swagger-core-api and per-server middlewares/plugins that build on top of swagger-core-api.

**Comment by diogeneshamilton** [comment]
@whitlockjc I use swagger-editor currently, and it seems that I must wait for it to be updated to use swagger-core-api in order to be usable with relative URLs. Am I getting that right?

**Comment by whitlockjc** [comment]
Yes.  We are in the process of migrating swagger-editor to swagger-core-api.  Also, supporting relative references for the swagger-editor will likely involve some other work since it's intended right now to be a single-file UI but this could change that.

**Comment by dkhanal** [comment]
I'm currently in the process of designing a fairly large set of APIs with various widgets/types reused. 

I'd like the Swagger Spec itself to be decomposed into one spec file per path referenced through $ref in YAML. Then the referenced spec file itself reference JSON schema definitions all through HTTP-based relative $ref's -- since the hostname would be tier/deployment-specific:

So (in pseudo-code):
```
myApiDoc.yaml:
    /my/resource/:
        $ref: "swagger-sppecs/myResource.json"

------

Schema definition in swagger-sppecs/myResource.json:
{
    "properties": {
        "propertyA": {
            "$ref":"../schema/propertyA.json"
        }
    }
}

------

Schema definition in schema/propertyA.json:
{
    "properties": {
        "propertyB": {
            "$ref":"../schema/propertyB.json"
        }
    }
}
```
My questions are:

1. With Swagger-Tools, is it possible to decompose/refactor YAML into specs (it looks like it is possible with the new changes)

2. With Swagger-Tools, is it possible to refactor the referenced JSON schemas themselves to utilize **relative** ref's in composite widgets and types? Ideally, I would like the schema library to be hosted externally, since the schema definitions could be utilized across technologies and applications.

Any thoughts on the current/upcoming capabilities or recommended patterns around this?

**Comment by whitlockjc** [comment]
The underlying library swagger-tools uses for JSON Reference resolution *([json-refs](https://github.com/whitlockjc/json-refs))* supports relative references but to use it requires swagger-tools to know where the loaded Swagger document came from, which it doesn't, and it needs a way to pass this information to json-refs.  To support this we need to alter all APIs to take an `options` object so that we can pass the location where the Swagger document was loaded from to json-refs.  There is one situation where this can work now but it is not something work documenting: If your relative references are relative to `process.cwd()` in Node.js or `window.location` in the browser.

**Comment by dkhanal** [comment]
Thank you for the response. I was able to get the Node side to work by making sure the relative refs were off-of `process.cwd()` like you suggested. However, neither Swagger UI nor Swagger Editor is able to expand the ref'ed schemas. Swagger UI just doesn't work, while Swagger Editor only shows the referenced relative URL for the model.

Is there any way to get Swagger Editor (or UI) to expand the schemas into a more human-friendly view (like it would if the definitions were local and not ref'ed)?

Regarding your comment on `window.location`, does that imply that the docs would have to served essentially off of `process.cwd()` for both node and Swagger Editor/UI to work?

**Comment by whitlockjc** [comment]
swagger-ui is its own thing and they do their own stuff.  swagger-editor uses swagger-tools but remember that references then become relative to `window.location` and I'm sure that the swagger-editor doesn't serve up any documents other than the one.  swagger-tools supporting relative references is just part of this as the whole tooling ecosystem needs to support it properly.

I'll work on getting swagger-tools to have an API for specifying the document root so relative references work universally.  Then it's up to swagger-editor and others to use the new support.

**Comment by dkhanal** [comment]
Thanks again for the response. So is your recommendation for now (until all tools in the ecosystem support the doc root) to just go with a single specification document with all references local to the doc?

Having one large YAML with thousands of lines of specification sounds rather monolithic to me -- so as a newcomer to swagger/tools, I would appreciate your insight on what the prevalent industry patterns are for composing a large set of APIs (essentially around reuse and physical refactoring of the specification document).

**Comment by whitlockjc** [comment]
What server environment are you using?

**Comment by dkhanal** [comment]
node + express

**Comment by whitlockjc** [comment]
So just Express and swagger-tools or something else?  How does swagger-editor and swagger-ui get into the mix?

**Comment by dkhanal** [comment]
I dropped Swagger UI for its inability to reference externally ref'ed schemas. 

I have a locally built Swagger Editor that I am hosting on a static server (different than where API would be hosted) -- just to use the UI portion of the editor. The editor portion is not used.

Swagger Editor worked great as long as the ref'd URIs were *absolute*. But I need them to be *relative* to support multiple deployment environments, and that's kind of where I'm hitting a roadblock.
 
The Node+Express side (even mocks) works just fine (even with relative refs).

Only alternative that seems to work with Swagger Editor/UI is to make the YAML spec a monolithic doc with no external or relative refs for schemas.

**Comment by glen-84** [comment]
@dkhanal Did you see [my comment](https://github.com/apigee-127/swagger-tools/issues/227#issuecomment-127729677) above?

Here is our Gulp file: https://gist.github.com/glen-84/f1bdda0bbe9c32da0d3f

**Comment by whitlockjc** [comment]
Yeah, the Node.js side of things should work because you got the resolution of references working due to changing your references to be relative to `process.cwd()`.  Everything on the Node.js side should work.  If you use the swagger-ui middleware in swagger-tools, it will serve the fully resolved document and a working swagger-ui for it.  @glen-84 has a working recipe as well to work around while we work on doing this in swagger-tools.

**Comment by dkhanal** [comment]
@glen-84  Thank you. I will play with this workaround.

@whitlockjc Thanks. Did you mean that swagger-ui middleware would serve a fully resolved document (even when there's relative refs) *currently*, or it will in the future?

**Comment by whitlockjc** [comment]
It does already, or it should.

**Comment by dkhanal** [comment]
@whitlockjc - No it doesn't appear to be working. It looks like the $ref's are expected to be relative to `process.cwd()` on the server (and the Node side works), but Swagger UI (served by the middleware) also needs the referenced schemas right off the root accessible from the browser. Not really a clean workaround, IMO. I wanted to `express.static(..)` the schema folder so that the browser could access it, but not sure how to get `express.static(..)` to work with swagger-express-mw. Looks like routes are overwritten by the middleware.

**Comment by dkhanal** [comment]
@glen-84 I used the swagger-parser tool and it finds the referenced files and everything but complains about a schema issue:

```
SyntaxError: Data does not match any schemas from "oneOf"
Data path: "/paths/~1user~1login/get/responses/200"
Schema path: "/properties/paths/patternProperties/^~1/properties/get/properties/responses/patternProperties/^([0-9]{3})$|^(default)$/oneOf"
]

Here's the YAML:

paths:
  /user/login:
    get:
      x-swagger-router-controller: "userApi_v1"
      consumes:
        - "application/json"
      produces:
        - "application/json"
        - "text/html"
        - "text/plain"
      description: "Authenticates the specified credentials."
      operationId: "login"
      parameters:
        - name: "username"
          in: "query"
          description: "Username to login as."
          required: true
          type: "string"
        - name: "password"
          in: "query"
          description: "Password to login with."
          required: true
          type: "string"
          format: "password"
        - name: "persistent"
          in: "query"
          description: "Indicates if the client chooses to have a persistent cookie."
          required: false
          type: "boolean"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "schema/json/user/v1/responses/loginResponse.json"
        default:
          description: "Error"
          schema:
            $ref: "schema/json/common/v1/standardError.json"

Here's the referenced loginResponse.json:

{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://myCompany.com/schema/json/user/v1/responses/loginResponse",
  "type": "string",
  "additionalProperties": false,
  "title": "Login Response",
  "name": "/"
}


```

**Comment by whitlockjc** [comment]
If you are willing to use swagger-parser, might as well use swagger-core-api since that's the successor to swagger-tools' API.  It supports relative references.

**Comment by dkhanal** [comment]
@glen-84 It looks like I now know why I'm getting the validation error. The $schema ref's apparently can't be full-blown JSON Schema Draft 4 objects. If I remove ` $schema, id, additionalProperties, and name` from the schema definition, then the tool works. The validation is probably done against the Swager 2.0 definition of 'schema', which doesn't support all of the JSON Draft 4 attributes.

@whitlockjc Thanks. Any ideas when swagger-core-api will be officially released? Is it near production?

**Comment by whitlockjc** [comment]
Within the next day or two.

**Comment by dkhanal** [comment]
Ok, sounds good. Can I use it with swagger-express-mw? Please let me know (or point me to doc) how it integrates with or replaces `SwaggerExpress.create(...)`

**Comment by whitlockjc** [comment]
No reason why you couldn't.  Here is an example:

```js
function configureServer (swaggerDoc) {
  // Do your server initialization here
}

require('swagger-core-api').create({
  definition: swaggerDocPath
}).then(function (swaggerApi) {
  // Configure server
  configureServer(swaggerApi.resolved);
}, function (err) {
  console.error(err.stack);
  process.exit(1);
});
```

**Comment by dkhanal** [comment]
Just tried to npm install (`npm install swagger-core-api --save`). It  picked up a package.json and an essentially empty index.js. Nothing else.

**Comment by whitlockjc** [comment]
`npm install https://github.com/apigee-127/swagger-core-api.git --save`.  Until I do the next release, the current NPM package is broken as it was created as a temporary placeholder.  I'll do an official release, probably with project rename to make it more intuitive.

**Comment by dkhanal** [comment]
Thanks... Installing now. Does it completely replace swagger-express-mw and swagger-tools? Is the CLI that generates the boilerplate going to use this for Node+Express? If so, should I completely do away with my SwaggerExpress.create() and use this instead?

**Comment by whitlockjc** [comment]
No, this is just an API for doing Swagger integrations.  It provides Swagger document loading (local/remote), reference resolution (local, remote, relative, etc.), document normalization (security requirements, path-level parameters, etc.) and APIs for interacting with the document.  For you, it would be used to load your document to work around swagger-tools not exposing what's necessary to handle relative references.

Pretty soon, after we release the project, we'll start rewriting the middlewares and exposing them individually with more support than just Connect and Connect-based/compatible servers.  Implementations should be much simpler this way.  I'll be writing a blog entry on where we're at and where we're going.

**Comment by dkhanal** [comment]
@whitlockjc Good stuff -- thanks! 

I tried the following. The UI is served with the YAML expanded/resolved to 1 level of depth, but ref's that are deeper (i.e. those present inside the referenced JSON schemas) are not resolved. 

Is there a way to get swagger-core-api to fully expand the document to the leaf level?

```
 SwaggerApi.create({definition: "./api/swagger/swagger.yaml"})
        .then(function (swaggerApi) {
            // Add swagger-ui (This must be before swaggerExpress.register)
            app.use(new SwaggerUi(swaggerApi.resolved));
        }, function (err) {
            console.error(err.stack);
            process.exit(1);
    });
```

**Comment by whitlockjc** [comment]
I assume you're talking about relative references?  With swagger-core-api, relative references work as the should so make sure they are relative to the documents loading them, not `process.cwd()` like you tried for swagger-tools'.

**Comment by dkhanal** [comment]
@whitlockjc Thanks, Jeremy -- I think I figured it out. Looks like the nested $ref's have to be relative to the file where they are referenced.

**Comment by whitlockjc** [comment]
That is correct.

**Comment by dkhanal** [comment]
@whitlockjc Jeremy -- You guys are working on very useful stuff. I'm up and running with swagger-core-api to serve fully resolved docs. Many thanks!

**Comment by whitlockjc** [comment]
Glad to help.

**Comment by ex-nerd** [comment]
I'm probably doing something wrong, but if I use `SwaggerApi.create` and then dump `swaggerApi.resolved` to a  JSON string, I still see stuff like
```json
{ "info": { "$ref": ".\/info\/index.yaml" } }
```
rather than the fully resolved value.

**Comment by whitlockjc** [comment]
I will look into it.

**Comment by ex-nerd** [comment]
Any update on this, or anything else we can do to help debug?

**Comment by whitlockjc** [comment]
Can you run something like this:

```js
SwaggerApi.create({...}).then(function (api) {
  console.log(api.references);
});
```

I want to see if the reference is unresolved.

**Comment by ex-nerd** [comment]
If I chdir into the directory containing my main `index.yaml`, I get:
```json
{"#/info":{"err":{},"missing":true,"ref":"./info/index.yaml"},"#/paths":{"err":{},"missing":true,"ref":"./paths/index.yaml"}}
```
If I pass in `swagger/index.yaml` as my source (which other conversation here suggested should work), I get:
```json
{"#/info":{"err":{"errno":-2,"code":"ENOENT","path":"info/index.yaml"},"missing":true,"ref":"./info/index.yaml"},"#/paths":{"err":{"errno":-2,"code":"ENOENT","path":"paths/index.yaml"},"missing":true,"ref":"./paths/index.yaml"}}
```
Both paths exist.

**Comment by whitlockjc** [comment]
Can you show me your `SwaggerApi.create` call?  If you use something like this, it *should* work:

```js
SwaggerApi.create({
  definition: path.join(__dirname, 'swagger', 'index.yaml')
});
```

**Comment by ex-nerd** [comment]
I switched things over to Sway yesterday, after the rename, but it's a grunt task that looks like this:

```javascript
    grunt.registerMultiTask('verifySwagger', 'Build our swagger docs into a single file', function() {
        var o = this.options();
        var Sway = require('sway');
        var done = this.async();
        //process.chdir(o.dir);
        Sway.create({definition: path.join(__dirname, o.dir, o.input)})
            .then(function (swaggerApi) {
                //grunt.fail.warn(process.cwd());
                grunt.fail.warn(JSON.stringify(swaggerApi.references));
                done();
            }, function (err) {
                done(err);
            });
```

With the `process.chdir` I get:

```json
{"#/info":{"err":{},"missing":true,"ref":"./info/index.yaml"},"#/paths":{"err":{},"missing":true,"ref":"./paths/index.yaml"}}
```

Without, I get:

```json
{"#/info":{"err":{"errno":-2,"code":"ENOENT","path":"info/index.yaml"},"missing":true,"ref":"./info/index.yaml"},"#/paths":{"err":{"errno":-2,"code":"ENOENT","path":"paths/index.yaml"},"missing":true,"ref":"./paths/index.yaml"}}
```

My day is booked with meetings but hopefully tomorrow I can spend some time to dig into Sway code to do some more detailed debugging.

**Comment by whitlockjc** [comment]
Can you show me your directory structure?  We have tests for this stuff in json-refs, the library that drives reference resolution and Swagger file loading and Mohsen wrote this: http://azimi.me/2015/07/16/split-swagger-into-smaller-files.html  Can you either show me your directory structure and/or create a sample project on GitHub that reproduces the issue?

**Comment by ex-nerd** [comment]
I must have commented on the wrong issue when I linked to this the other day...  I set my example up here: https://github.com/ex-nerd/swagger-example

**Comment by whitlockjc** [comment]
If I understand, is this just an example or is there an error to fix?  When I run your code, it works as expected from what I can tell.

**Comment by ex-nerd** [comment]
I'm not seeing the `$ref` stuff being parsed properly unless I use `json-refs` directly.  if you run `grunt test` it prints out something similar to the error messages I mentioned earlier in this issue.

**Comment by whitlockjc** [comment]
So, it looks like there were two bugs in sway and they've been fixed: https://github.com/apigee-127/sway/blob/master/RELEASE_NOTES.md#v021-2015-08-26  If you install the latest sway release, this should be fixed.  I did test your example and here is the code I used:

```js
Sway.create({definition: './swagger/index.yaml'})
  .then(function (api) {
    // Your code here
  });
```

**Comment by whitlockjc** [comment]
Sorry about that.  json-refs heavily tests relative references and JSON/YAML references so I didn't have a lot of tests in sway for this.

**Comment by ex-nerd** [comment]
Confirmed that it works, though I'm no longer getting any errors in the Sway.create() promise, even with a broken path for my `info` section.  The `then` clause is called and the resolved data looks something like:

```json
{"swagger":"2.0","info":{"$ref":"./info/this_path_doesnt_exist.yaml"}, ...
```

**Comment by whitlockjc** [comment]
It's expected.  sway does not validate on create so unresolvable references are left as-is.  If you call the validate method, you'll see it returns false and getLastErrors will return the unresolvable references.  Remember, you're using this as a workaround and the middleware I'm working on to replace the swagger-tools' equivalents will be done soon.  They will be drop in replacements so don't worry.

**Comment by whitlockjc** [comment]
Sorry about the formatting...I'm mobile.

**Comment by ex-nerd** [comment]
Gotcha.  I forgot to mention that I assumed it was expected.  I tried to hook into the validation stuff from swagger-tools directly but ran out of time during the work day (and my javascript-fu is fairly weak these days).  Hoping I can eventually get a nice Gruntfile designed to develop/build/test any swagger API, but it sounds like you may beat me to it and just make something like that part of the standard feature set.

**Comment by whitlockjc** [comment]
Well, the plan has been to take what we learned from swagger-tools and break up the project a little bit.  sway is the API part of swagger-tools, rewritten.  It is complete for the first pass.  We now need to create the replacement middleware and that is when you'll see us doing the pre-startup validation that will do this stuff for you.  You can work around it as described above but you're already using sway to work around swagger-tools' lack of support for relative references so you might be better off waiting a few days so I can get [sway-connect](https://github.com/apigee-127/sway-connect) released.

**Comment by ex-nerd** [comment]
Any update on this?  I see that it's been about a month since you suggested you might have sway-connect ready.  Anything I can do to help?

**Comment by whitlockjc** [comment]
Sorry for the delay.  Since swagger-node uses swagger-tools, I have to get this done.  Give me a few days and I'll publish a release that fixes this in a way that swagger-node can consume.

**Comment by whitlockjc** [comment]
I've pushed the first pass at this.  I've updated all relevant documentation but here is the short version: All APIs *(core and middleware initialization)* have been updated to have an optional `options` argument immediately before the `callback` argument.  This `options` object will allow you to set `options.jsonRefs.location` to the base directory/url where your Swagger document was loaded.

Could any of you verify this works for you?  I've got middleware initialization tests, tests for all APIs and things seem to work but I'd like to hear from someone else prior to doing a release.

**Comment by whitlockjc** [comment]
Seems there are a few more quirks to work out.  I'm in the process of testing this from the CLI and it's not working right.

**Comment by whitlockjc** [comment]
I've decided to blow away my efforts on this.  I've worked on this all day and the deeper it gets, the more things break.  Due to the internal meta-model required to support Swagger 1.2 and 2.0, to touch anything related to references is to break it.  This is not an excuse but doing this is much, much larger than originally anticipated.  Sorry for the disappointment but this likely isn't possible without a rewrite.

**Comment by mershal** [comment]
For me, the schema were resolved if I ran the code from a specific directory - the one that contains my `app.js` file. Whenever I tried to run my code from another directory using gulp to run my dist or tests it failed because it couldn't resolve the relative schema. A workaround that worked for me is to set the `cwd` to `__dirname` at the beginning of my `app.js` (using `process.chdir(__dirname)`) file, so when I initialize my swagger docs everything works.

**Comment by samskiter** [comment]
just a :+1: for nested ref support. not possible to have the path from the referencing file if the referenced file is in a submodule that we reuse.

**Comment by whitlockjc** [comment]
I just updated json-refs to `2.0.x` and that will help but I think the real solution will be to rewrite swagger-tools' internals which is not happening right now.  I might see if I can do a sway-based rewrite over the weekend.

**Comment by whitlockjc** [comment]
I've got a better solution for this as a workaround until either this gets solved in swagger-tools or swagger-tools is finally deprecated by sway and sway-connect:

```js
var JsonRefs = require('json-refs');
var SwaggerTools = require('swagger-tools');
var YAML = require('js-yaml');

JsonRefs.resolveRefsAt('./api/swagger/swagger.yaml', {
  // Resolve all remote references
  filter: ['relative', 'remote'],
  loaderOptions: {
    processContent: function (res, cb) {
      cb(undefined, YAML.safeLoad(res.text));
    }
  }
})
  .then(function (results) {
    SwaggerTools.initializeMiddleware(results.resolved, function (middleware) {
      // Wire up the Swagger middleware
    });
  })
  .catch(function (err) {
    console.error(err.stack);
    process.exit(1);
  });
```

I'll see if I can work this into swagger-tools without having to rewrite it.  I know the CLI and Middleware are easy fixes but the APIs, as they are now, would require a rewrite to allow you to support references.

**Comment by whitlockjc** [comment]
What would you all think if I were to blow away the API portion of swagger-tools, since [sway](https://github.com/apigee-127/sway/blob/master/docs/API.md) provides a _real_ API, and just get the swagger-tools CLI/Middleware to use the approach mentioned above, or even sway?

I'm tired of these issues that require rewrites just sitting here but the rewrite itself doesn't make much sense knowing that swagger-tools the API is no longer useful as sway is much better.  Want to use sway with Swagger 1.2?  Convert the document via the swagger-converter API and then use the sway API.

Thoughts?

**Comment by dkhanal** [comment]
Has anything changed recently with Sway in the way it resolves relative references from within JSON schemas:

```
SwaggerExpress.create(config, function(err, swaggerExpress) {
  if (err) { throw err; }

  Sway.create({definition: "./api/swagger/swagger.yaml"})
      .then(function (swaggerApi) {
        app.use(new SwaggerUi(swaggerApi.resolved));
      }, function (err) {
        console.error(err.stack);
        process.exit(1);
      });

  swaggerExpress.register(app);

  var port = process.env.PORT || 10010;
  var server = app.listen(port);

  console.log('Server listening at: ' + server.address().address + ':' + server.address().port);
});
```
I get the following error when I start the project:

`
Error initializing middleware
Error: Swagger document(s) failed validation so the server cannot start
`
If I remove the relative reference from within JSON, it works. Otherwise it fails. The relative reference is correct and the referenced file is present.

This used to work OK until a couple months ago.

**Comment by whitlockjc** [comment]
Upgrade, I released a fix Friday.

**Comment by dkhanal** [comment]
Thanks. I just upgraded Sway. Still get the same error with `"sway": "^0.6.0"`. Anything else that must be upgraded?

**Comment by whitlockjc** [comment]
I meant to upgrade swagger-tools.  Sway hasnt seen a release and shouldn't be causing issues.

**Comment by dkhanal** [comment]
Upgraded swagger-tools. At `"swagger-tools": "^0.9.14"` still see the issue.

**Comment by whitlockjc** [comment]
Try using Sway at master then.  I'm not sure what is up because Sway hasn't had any releases to cause any problems and swagger-tools is not doing anything for relative references still.  The approach I documented above is probably better but I'm not sure why something just started failing.  Run with `DEBUG=swagger-tools*` to get more information on what the failure is.

**Comment by dkhanal** [comment]
`DEBG=swagger-tools*` did not provide anything of much value (first 3 lines below) . The stack looks like this:
```
swagger-tools:middleware Initializing middleware +0ms
swagger-tools:middleware   Identified Swagger version: 2.0 +0ms
swagger-tools:middleware   Validation: failed +234ms
Error initializing middleware
Error: Swagger document(s) failed validation so the server cannot start
  at ...\node_modules\swagger-tools\index.js:72:13
    at cbWrapper (...\node_modules\swagger-tools\lib\specs.js:1035:5)
    at validateSwagger2_0 (...\node_modules\swagger-tools\lib\specs.js:1030:3)
    at validateSemantically (...\node_modules\swagger-tools\lib\specs.js:1040:5)
    at ...\node_modules\swagger-tools\lib\specs.js:1233:7
    at ...\node_modules\swagger-tools\lib\specs.js:1073:29
    at ...\node_modules\swagger-tools\lib\specs.js:719:12
    at ...\node_modules\swagger-tools\lib\specs.js:695:9
```

**Comment by dkhanal** [comment]
Also, why is SwaggeExpress.create()  does not seem to follow the callback pattern for errors. Here's a simplified example:
```
SwaggerExpress.create(config, function(err, swaggerExpress) {
    console.log('AFTER SwaggerExpress.create()');
    if (err){
        console.log('There was an ERROR.');
    }
    else
    {
        console.log('There was NO ERROR.');
    }
});
```
And here's the output (it never gets to the callback function). It seems to be throwing, instead.

```
BEFORE SwaggerExpress.create()
Error initializing middleware
Error: Swagger document(s) failed validation so the server cannot start
at ...\node_modules\swagger-tools\index.js:72:13
at cbWrapper (...\node_modules\swagger-tools\lib\specs.js:1035:5)
at validateSwagger2_0 (...\node_modules\swagger-tools\lib\specs.js:1030:3)
at validateSemantically (...\node_modules\swagger-tools\lib\specs.js:1040:5)
at ...\node_modules\swagger-tools\lib\specs.js:1233:7
at ...\node_modules\swagger-tools\lib\specs.js:1073:29
at ...\node_modules\swagger-tools\lib\specs.js:719:12
at ...\node_modules\swagger-tools\lib\specs.js:695:9
```

**Comment by dkhanal** [comment]
Here's another finding that may be helpful. 

It looks like the relative references (`$ref` from one schema file to another) are expected to be relative to the application root. 

Previously, I believe the relative references (`$ref` from one schema file to another) were relative to the schema file containing the `$ref` declaration.

If I change my `$ref`s to now make them relative to the application root, it seems to work.

Was this a breaking change that was introduced recently?

**Comment by dkhanal** [comment]
Some more information:

I have a fairly succinct `.yaml` file where each `path` contains a `$ref` to Swagger Specification (in JSON) for the path. Each such specification, then references various other schema (in JSON) files for parameters and responses. Then each schema definition contains one or more `$ref`'s pointing to reusable/common constructs.

**This is the working configuration:**

`$ref`'s in the swagger.yaml definition are relative to application root. 
`$ref`'s in the Swagger Specification JSON (e.g. for parameters and responses) are relative to the specification file containing the `$ref`.
`$ref`'s in the JSON schema files that point to other JSON schema for reusable constructs are relative to application root. It looks like this is what changed recently. These `$ref`'s, I believe used to be relative to the current schema file (i.e. file containing this `$ref`).

For example, in the following snippet of a JSON schema, the `meta` property's `$ref` must be relative to the application root, rather than relative to the file containing the `$ref`:

```
...
...
    },
    "meta": {
      "$ref": "specs/schema/v1/meta.json"
    }
  },
  "required": [
    "data"
  ]
}
```

**Comment by whitlockjc** [comment]
swagger-tools and sway are really old so the chances they have bugs does not surprise me.  The more interesting dependency version would be `json-refs`.  Also, you'd be much better off just not using sway and instead using `json-refs` with the code snippet I pasted above a few days ago.

Upgrading swagger-tools will give you better output for the failure you're seeing.  You can also run `swagger-tools validate YOUR_FILE` and it will let you know the failures as well.

**Comment by DannyiCracked** [comment]
`Project Errors
--------------
#/paths: Additional properties not allowed: $ref
Results: 1 errors, 0 warnings`

Are $ref's to other files going to be supported soon?

`swagger: "2.0"
info:
  version: "0.0.1"
  title: Test
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make productio  n-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - multipart/form-data
  - application/x-www-form-urlencoded
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  $ref: ./controllers/program.yaml`

Inside `controllers/program.yaml` exists the code you would expect to see under the `paths:` definition.

The error comes from both swagger-tools cli and swagger-node cli validation.

**Comment by whitlockjc** [comment]
Will you please read some of the comments before yours?  Not only is the answer to your question there but so is the workaround.

On another note, Swagger forbids `$ref` where you have it so some might say I should be throwing an error there anyways: https://github.com/apigee-127/sway/issues/62

**Comment by dexwiz** [comment]
Is there a way to set Json-Ref's options.relativeBase from swagger-tools.initializeMiddleware(doc, cb())?  I have split by yaml files, but I have to include the full paths for every reference. I would like to be able to set a relative base for the docs instead.

**Comment by whitlockjc** [comment]
This is the problem with the current swagger-tools API.  To allow for you to pass options downstream, every API has to change and that is a breaking change.  So I'd have to release `1.0.0` just to support it.  That's why I've instead suggested the workarounds above until I can get `sway-connect` out the door.  Thanks for your patience.

**Comment by dexwiz** [comment]
Thanks for the quick update, good to know!

**Comment by dmk255** [comment]
Hello! Is there any update on this? I'd love to be able to split up my swagger.yaml file into multiple directories (e.g. paths, definitions, etc.)

**Comment by towertop** [comment]
This problem still exists in current version.

I saw json-ref has an additional option 'relativeBase' but spec.js doesn't pass in this option.

As for the amount of invocations in spec.js or other files demanded to modify, I suggest to add a new method in json-ref specified for initial default options globally, including 'relativeBase'. Adding a wrapper above json-ref should also do. This way might ease the code work.

**Comment by whitlockjc** [comment]
Of course this problem still exists, the issue is still open.  The suggested workaround is all you will get for now because rewriting swagger-tools to support this isn't going to happen.  I mentioned this above.  Just use `json-refs` to resolve your document and _then_ use the resolved document when providing the Swagger document to the swagger-tools functions.

**Comment by canercandan** [comment]
Here is another workaround for those who want to use `json-refs` with the [swagger-node express skeletons](https://github.com/swagger-api/swagger-node/blob/master/project-skeletons/express/app.js):

```
var JsonRefs = require('json-refs');
var YAML = require('js-yaml');
var SwaggerExpress = require('swagger-express-mw');
var app = require('express')();
// export setup Promis for testing
module.exports = new Promise(function (resolve, reject) {

  JsonRefs.resolveRefsAt('./api/swagger/swagger.yaml', {
    // Resolve all remote references
    filter: ['relative', 'remote'],
    loaderOptions: {
      processContent: (res, cb) => cb(undefined, YAML.safeLoad(res.text))
    }
  })
    .then(results => {
      var config = {
        appRoot: __dirname, // required config
        swagger: results.resolved
      };

      SwaggerExpress.create(config, function (err, swaggerExpress) {
        if (err) { throw err; }

        // install middleware
        swaggerExpress.register(app);

        var port = process.env.PORT || 10010;
        app.listen(port, function() {
          if (swaggerExpress.runner.swagger.paths['/hello']) {
            console.log('try this:\ncurl http://127.0.0.1:' + port + '/hello?name=Scott');
          }
          resolve(app);
        });
      });
    })
    .catch(function (err) {
      console.error(err.stack);
      process.exit(1);
    });
  ;
});
```

**Comment by jnazander** [comment]
@canercandan thank you very much for the workaround!

@whitlockjc So I guess there will be no fix at all? Did you already close the lid on this one?
